export const CREATED_SUCCESS = "CREATED_SUCCESS";
export const RETRIEVE_SUCCESS = "RETRIEVE_SUCCESS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const CREATED_FAIL = "CREATED_FAIL";
export const RETRIEVE_FAIL = "RETRIEVE_FAIL";
export const DELETE_FAIL = "DELETE_FAIL";
export const UPDATE_FAIL = "UPDATE_FAIL";
